version: "3"
services:
  testdb:
    image: postgres
    restart: always
    container_name: user_db
    environment:
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=mysecretpassword"
      - "POSTGRES_DB=user_db"
    ports:
      - 4001:5432